### ISSUE TITLE
Memory leak/unsubscribing does not work

### ISSUE THREAD

**Issue by aloker** [omer-g/persistent-svelte-store#1]
I haven't tested it in practice, but from reading the code I'd say unsubscribing from the store does not work.

https://github.com/omer-g/persistent-svelte-store/blob/866f223044a616dc994b8baf0f7ed90174f7671b/persistentStore.ts#L32-L34

The result of `filter` is not assigned to `subscriptions`, so the subscriptions array only grows but is never cleaned up. NB: `filter` does not mutate the array that it's called on but returns a new, filtered array.

**Comment by omer-g** [comment]
Thank you! I've pushed a commit that corrects this.
